# Generated by Django 5.0.3 on 2024-03-22 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimingAnalysisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timing_analysis_data', to='api.request')),
            ],
        ),
    ]
