# Generated by Django 5.0.3 on 2024-03-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_timinganalysisdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='timinganalysisdata',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
